[package]
name = "math-with-rust"
version = "0.1.0"
edition = "2018"

[lib]
crate-type=["cdylib"]

[dependencies]
plotters = "0.3.1"
plotters-canvas = "^0.3.*"
wasm-bindgen = "0.2.62"
wee_alloc = "0.4.5"
web-sys = { version = "0.3.39", features = ["HtmlCanvasElement"] }
